---
title: "Preliminary Analysis for ASHP Abstract"
author: "Rebecca Kessinger, Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
options(knitr.table.format = "html")
```

```{r}
library(tidyverse)
library(stringr)
library(kableExtra)

x <- dirr::get_rds("../data/final")
```

```{r}
count_pts <- data_rk %>%
    count(med)

x <- paste("n =", count_pts$n[[1]])
y <- paste("n =", count_pts$n[[2]])

hdr_total <- c(" " = 1, x = 2, y = 2)
names(hdr_total) <- c(" ", x, y)
```

```{r}
data_demographics_rk %>%
    left_join(data_rk[c("millennium.id", "med")], by = "millennium.id") %>%
    group_by(med) %>%
    summarize_at(c("age", "length.stay"), funs(mean, sd)) %>%
    gather(var_name, result, -med) %>%
    separate(var_name, c("var_name", "measure"), sep = "_") %>%
    spread(measure, result) %>%
    unite(mean_sd, mean, sd) %>%
    spread(med, mean_sd) %>%
    separate(rivaroxaban, c("doac_mean", "doac_sd"), sep = "_") %>%
    separate(warfarin, c("warf_mean", "warf_sd"), sep = "_") %>%
    mutate_at(c("doac_mean", "doac_sd", "warf_mean", "warf_sd"), as.numeric) %>%
    mutate_at("var_name", str_replace_all, pattern = c("age" = "Age (years)", "length.stay" = "Length of stay, index hospitalization (days)")) %>%
    rename(Variable = var_name,
           Mean = doac_mean,
           SD = doac_sd,
           Mean = warf_mean,
           SD = warf_sd) %>%
    knitr::kable(digits = 0, caption = "Baseline characteristics") %>%
    kable_styling() %>%
    add_header_above(header = hdr_total) %>%
    add_header_above(c("", "Rivaroxaban" = 2, "Warfarin" = 2)) 
```

```{r}
df_gender <- data_demographics_rk %>%
    left_join(data_rk[c("millennium.id", "med")], by = "millennium.id") %>%
    filter(!is.na(gender),
           gender == "Male") %>%
    count(med, gender) %>%
    rename(var_name = gender, 
           result = n) %>%
    left_join(count_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) 

df_race <- data_demographics_rk %>%
    left_join(data_rk[c("millennium.id", "med")], by = "millennium.id") %>%
    mutate_at("race", funs(coalesce(., "Unknown"))) %>%
    filter(!is.na(race)) %>%
    count(med, race) %>%
    rename(var_name = race, 
           result = n) %>%
    left_join(count_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    arrange(desc(doac_pct))

df_indication <- data_rk %>%
    group_by(med) %>%
    summarize_at(c("afib", "dvt", "pe"), sum, na.rm = TRUE) %>%
    mutate_at(c("afib", "dvt", "pe"), funs(coalesce(., 0L))) %>%
    rename(A.fib = afib,
           DVT = dvt,
           PE = pe) %>%
    gather(var_name, result, -med) %>%
    left_join(count_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    arrange(desc(doac_pct))

 df_gender %>%
    bind_rows(df_race, df_indication) %>%
    rename(Variable = var_name,
           n = doac_result,
           `%` = doac_pct,
           n = warf_result,
           `%` = warf_pct) %>%
    knitr::kable(digits = 0, caption = "Baseline demographics") %>%
    kable_styling() %>%
    add_header_above(header = hdr_total) %>%
    add_header_above(c("", "Rivaroxaban" = 2, "Warfarin" = 2)) %>%
    group_rows("Race", 2, nrow(df_race) + 1, label_row_css = "") %>%
    group_rows("Indication for Anticoagulation[note]", nrow(df_race) + 2, nrow(df_race) + nrow(df_indication) + 1, label_row_css = "") %>%
    add_footnote("Patients may have more than one indication", "symbol")
    
```

```{r}
data_rk %>%
    mutate(revisit = !is.na(revisit_days),
           revisit_30 = revisit_days <= 30,
           readmit = revisit.type == "Inpatient",
           readmit_30 = readmit & revisit_30) %>%
    group_by(med) %>%
    summarize_at(c("revisit", "revisit_30", "readmit", "readmit_30"), sum, na.rm = TRUE) %>%
    mutate_at(c("revisit", "revisit_30", "readmit", "readmit_30"), funs(coalesce(., 0L))) %>%
    rename(`a_Revisit within 30 days` = revisit_30,
           `b_Revisit within 90 days` = revisit,
           `c_Readmission within 30 days` = readmit_30,
           `d_Readmission within 90 days` = readmit) %>%
    gather(var_name, result, -med) %>%
    left_join(count_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    mutate_at("var_name", str_replace_all, pattern = "^._", replacement = "") %>%
    rename(Variable = var_name,
           n = doac_result,
           `%` = doac_pct,
           n = warf_result,
           `%` = warf_pct) %>%
    knitr::kable(digits = 0, caption = "Preliminary results") %>%
    kable_styling() %>%
    add_header_above(header = hdr_total) %>%
    add_header_above(c("", "Rivaroxaban" = 2, "Warfarin" = 2)) %>%
    group_rows("Primary endpoint", 1, 2, label_row_css = "") %>%
    group_rows("Secondary endpoint", 3, 4, label_row_css = "")
```

```{r}
count_revisit_pts <- data_rk %>%
    filter(!is.na(revisit_days)) %>%
    count(med)

x <- paste("n =", count_revisit_pts$n[[1]])
y <- paste("n =", count_revisit_pts$n[[2]])

hdr_revisit <- c(" " = 1, x = 2, y = 2)
names(hdr_revisit) <- c(" ", x, y)

df_revisit_type <- data_rk %>%
    filter(!is.na(revisit_days)) %>%
    count(med, revisit.type) %>%
    rename(var_name = revisit.type, 
           result = n) %>%
    left_join(count_revisit_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    mutate_if(is.numeric, funs(coalesce(., 0))) %>%
    arrange(desc(doac_pct), var_name)

df_revisit_details <- data_rk %>%
    filter(!is.na(revisit_days)) %>%
    mutate(same_facility = revisit.facility == "Memorial Hermann Hospital") %>%
    group_by(med) %>%
    summarize_at(c("revisit_anticoag_related", "new_bleed", "new_thrombus", "same_facility"), sum, na.rm = TRUE) %>%
    mutate_at(c("revisit_anticoag_related", "new_bleed", "new_thrombus", "same_facility"), funs(coalesce(., 0L))) %>%
    rename(`a_Revisit was anticoagulation-related` = revisit_anticoag_related,
           `b_New bleeding on revisit` = new_bleed,
           `c_New thrombosis on revisit` = new_thrombus,
           `d_Revisit to index hospital` = same_facility) %>%
    gather(var_name, result, -med) %>%
    left_join(count_revisit_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    mutate_at("var_name", str_replace_all, pattern = "^._", replacement = "")

df_revisit_details %>%
    bind_rows(df_revisit_type) %>%
    rename(Variable = var_name,
           n = doac_result,
           `%` = doac_pct,
           n = warf_result,
           `%` = warf_pct) %>%
    knitr::kable(digits = 0, caption = "Findings among patients with a revisit within 90 days") %>%
    kable_styling() %>%
    add_header_above(header = hdr_revisit) %>%
    add_header_above(c("", "Rivaroxaban" = 2, "Warfarin" = 2)) %>%
    group_rows("Revisit Encounter Type", nrow(df_revisit_details) + 1, nrow(df_revisit_details) + nrow(df_revisit_type), label_row_css = "") 
```

```{r}
count_revisit_pts <- data_rk %>%
    filter(revisit_days <= 30) %>%
    count(med)

x <- paste("n =", count_revisit_pts$n[[1]])
y <- paste("n =", count_revisit_pts$n[[2]])

hdr_revisit <- c(" " = 1, x = 2, y = 2)
names(hdr_revisit) <- c(" ", x, y)

df_revisit_type <- data_rk %>%
    filter(revisit_days <= 30) %>%
    count(med, revisit.type) %>%
    rename(var_name = revisit.type, 
           result = n) %>%
    left_join(count_revisit_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    mutate_if(is.numeric, funs(coalesce(., 0))) %>%
    arrange(desc(doac_pct), var_name)

df_revisit_details <- data_rk %>%
    filter(!is.na(revisit_days)) %>%
    group_by(med) %>%
    summarize_at(c("revisit_anticoag_related", "new_bleed", "new_thrombus"), sum, na.rm = TRUE) %>%
    mutate_at(c("revisit_anticoag_related", "new_bleed", "new_thrombus"), funs(coalesce(., 0L))) %>%
    rename(`a_Revisit was anticoagulation-related` = revisit_anticoag_related,
           `b_New bleeding on revisit` = new_bleed,
           `c_New thrombosis on revisit` = new_thrombus) %>%
    gather(var_name, result, -med) %>%
    left_join(count_revisit_pts, by = "med") %>%
    mutate(pct = result / n * 100) %>%
    select(-n) %>%
    unite(result_pct, result, pct) %>%
    spread(med, result_pct) %>%
    separate(rivaroxaban, c("doac_result", "doac_pct"), sep = "_") %>%
    separate(warfarin, c("warf_result", "warf_pct"), sep = "_") %>%
    mutate_at(c("doac_result", "doac_pct", "warf_result", "warf_pct"), as.numeric) %>%
    mutate_at("var_name", str_replace_all, pattern = "^._", replacement = "")

df_revisit_details %>%
    bind_rows(df_revisit_type) %>%
    rename(Variable = var_name,
           n = doac_result,
           `%` = doac_pct,
           n = warf_result,
           `%` = warf_pct) %>%
    knitr::kable(digits = 0, caption = "Findings among patients with a revisit within 30 days") %>%
    kable_styling() %>%
    add_header_above(header = hdr_revisit) %>%
    add_header_above(c("", "Rivaroxaban" = 2, "Warfarin" = 2)) %>%
    group_rows("Revisit Encounter Type", nrow(df_revisit_details) + 1, nrow(df_revisit_details) + nrow(df_revisit_type), label_row_css = "") 
```
